from selenium.webdriver.common.by import By

sign_in_button = ".//button[text()='Войти в аккаунт']"
register_button = ".//a[text()='Зарегистрироваться']"
login_field_input = ".//label[text()='Имя']/following::input[1]"
email_field_input = ".//label[text()='Email']/following::input[1]"
password_field_input = ".//label[text()='Пароль']/following::input[1]"
submit_register_button = ".//button[text()='Зарегистрироваться']"
log_in_button = "[class='button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa']"
personal_account_button = ".//p[@class='AppHeader_header__linkText__3q_va ml-2' and text()='Личный Кабинет']"
profile_button_in_menu = ".//a[text()='Профиль']"
customer_name_in_profile = ".//input[@value='Liudmila']"
email_login_field = "[type='text']"
password_login_field = "[type='password']"
error_password_alert = "[class='input__error text_type_main-default']"
enter_to_profile_button_on_registration_page = "[class='Auth_link__1fOlj']"
restore_password_button = ".//a[text()='Восстановить пароль']"
exit_button = "[class='Account_button__14Yp3 text text_type_main-medium text_color_inactive']"
constructor_button = ".//p[@class='AppHeader_header__linkText__3q_va ml-2' and text()='Конструктор']"
collect_burger_header = ".//h1[text()='Соберите бургер']"
burger_logo = "[class='AppHeader_header__logo__2D0X2']"
buns_section_in_constructor = ".//span[text()='Булки']/parent::div"
cards_with_buns = ".//ul[@class='BurgerIngredients_ingredients__list__2A-mT']//p[contains(text(),'булка')]"
sauses_section_in_constructor = ".//span[text()='Соусы']/parent::div"
cards_with_sauses = ".//ul[@class='BurgerIngredients_ingredients__list__2A-mT']//p[contains(text(),'Соус')]"
fillings_section_in_constructor = ".//span[text()='Начинки']/parent::div"
cards_with_fillings = ".//h2[text()='Начинки']"


